package main

import (
	"context"
	"fmt"
	"os"

	"github.com/gsoultan/thoth/document"
	"github.com/gsoultan/thoth/excel"
)

func main() {
	ctx := context.Background()

	// Create a new Excel document
	doc := excel.NewDocument().(document.Spreadsheet)
	defer doc.Close()

	doc.SetMetadata(document.Metadata{
		Title:   "Advanced Production Report v2",
		Author:  "Thoth Advanced Engine",
		Subject: "Data Tables and Print Settings",
	})

	sheet, _ := doc.Sheet("Sales Data")

	// 1. Setup Table Data
	headers := []string{"Region", "Q1", "Q2", "Q3", "Q4", "Total"}
	for i, h := range headers {
		colName := string(rune('A' + i))
		sheet.Cell(colName + "1").Set(h).Style(document.CellStyle{Bold: true, Background: "D9D9D9"})
	}

	regions := []string{"North", "South", "East", "West", "Central"}
	for i, r := range regions {
		row := i + 2
		sheet.Cell(fmt.Sprintf("A%d", row)).Set(r)
		sheet.Cell(fmt.Sprintf("B%d", row)).Set(1000 + i*100)
		sheet.Cell(fmt.Sprintf("C%d", row)).Set(1100 + i*150)
		sheet.Cell(fmt.Sprintf("D%d", row)).Set(1200 + i*200)
		sheet.Cell(fmt.Sprintf("E%d", row)).Set(1300 + i*250)
		sheet.Cell(fmt.Sprintf("F%d", row)).Formula(fmt.Sprintf("SUM(B%d:E%d)", row, row))
	}

	// 2. Add Excel Table (ListObject)
	// This provides structured data, auto-filters, and styling.
	sheet.AddTable("A1:F6", "SalesTable")

	// 3. Print Settings
	// Set Print Area to only include the table
	sheet.SetPrintArea("A1:F6")
	// Repeat headers at the top of every page
	sheet.SetPrintTitles("1:1", "")

	// 4. Page Setup
	sheet.SetPageSettings(document.PageSettings{
		PaperType:   document.PaperA4,
		Orientation: document.OrientationLandscape,
		Margins: document.Margins{
			Top: 72, Bottom: 72, Left: 36, Right: 36, // in points (1 inch and 0.5 inch)
		},
	})

	// 5. Header & Footer
	sheet.SetHeader("&LConfidential&CQuarterly Report&RPage &P of &N")
	sheet.SetFooter("&LGenerated by Thoth&RExport Date: &D")

	// 6. Protection
	doc.SetPassword("supersecret") // Workbook protection
	sheet.Protect("sheetsecret")   // Worksheet protection

	// 7. Grouping
	sheet.GroupRows(2, 6, 1) // Group regional data

	// Save
	f, err := os.Create("advanced_v2_report.xlsx")
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		return
	}
	defer f.Close()

	if err := doc.Save(ctx, f); err != nil {
		fmt.Printf("Error saving document: %v\n", err)
		return
	}

	fmt.Println("Advanced Excel report v2 generated: advanced_v2_report.xlsx")
}
