package main

import (
	"context"
	"fmt"
	"os"

	"github.com/gsoultan/thoth/document"
	"github.com/gsoultan/thoth/word"
)

func main() {
	ctx := context.Background()

	// Create a new Word document
	doc := word.NewDocument().(document.WordProcessor)
	defer doc.Close()

	// 1. Metadata and Page Settings
	doc.SetMetadata(document.Metadata{
		Title:  "Advanced Layout Demo",
		Author: "Junie AI",
	})

	// 2. Advanced Header and Footer
	doc.SetHeader("ADVANCED LAYOUT - CONFIDENTIAL", document.CellStyle{Horizontal: "center", Bold: true, Color: "FF0000"})
	doc.SetFooter("Generated by Thoth Go Library", document.CellStyle{Horizontal: "right", Italic: true})

	// 3. Advanced Heading with Styling
	doc.AddHeading("Advanced Document Layout & Styling", 1, document.CellStyle{
		Bold:         true,
		Color:        "2F5496",
		SpacingAfter: 12,
		Horizontal:   "center",
	})

	doc.AddParagraph("This document demonstrates advanced layout, complex table structures, and detailed styling available in Thoth.",
		document.CellStyle{Italic: true, Horizontal: "center"})

	// 4. Advanced Table Layout (Merging, Borders, Shading, Alignment)
	doc.AddHeading("1. Advanced Table Layout", 2)

	// Complex table with 5x5 grid
	table, err := doc.AddTable(5, 5)
	if err != nil {
		fmt.Printf("Error adding table: %v\n", err)
		return
	}

	table.SetStyle("TableGrid").SetColumnWidths(1.0, 1.5, 1.0, 1.0, 1.0)
	// Header row - will try to implement SetHeaderRows
	table.SetHeaderRows(1)

	headerStyle := document.CellStyle{Bold: true, Background: "E7E6E6", Horizontal: "center", Vertical: "center"}
	table.Row(0).Cell(0).AddParagraph("ID", headerStyle)
	table.Row(0).Cell(1).AddParagraph("Feature", headerStyle)
	table.Row(0).Cell(2).AddParagraph("Status", headerStyle)
	table.Row(0).Cell(3).AddParagraph("Version", headerStyle)
	table.Row(0).Cell(4).AddParagraph("Notes", headerStyle)

	// Merge cells for a group heading (Horizontal Merge)
	table.Row(1).Cell(0).AddParagraph("CORE", document.CellStyle{Bold: true, Horizontal: "center"})
	table.MergeCells(1, 0, 1, 5) // Merge Row 1, Cols 0-4

	// Row with different cell styling
	table.Row(2).Cell(0).AddParagraph("001")
	table.Row(2).Cell(1).AddParagraph("Advanced Tables")
	table.Row(2).Cell(2).AddParagraph("Verified", document.CellStyle{Color: "00B050", Bold: true})
	table.Row(2).Cell(3).AddParagraph("v1.2")
	table.Row(2).Cell(4).AddParagraph("Standard grid")

	// Vertical merge demo
	table.MergeCells(3, 0, 2, 1) // Row 3, Col 0, spans 2 rows
	table.Row(3).Cell(0).AddParagraph("MULTI", document.CellStyle{Bold: true, Vertical: "center", Horizontal: "center"})

	table.Row(3).Cell(1).AddParagraph("Vertical Merging")
	table.Row(3).Cell(2).AddParagraph("Implemented", document.CellStyle{Color: "0070C0"})
	table.Row(3).Cell(3).AddParagraph("v1.2")
	table.Row(3).Cell(4).AddParagraph("Spans 2 rows")

	table.Row(4).Cell(1).AddParagraph("Horizontal + Vertical")
	table.Row(4).Cell(2).AddParagraph("WIP", document.CellStyle{Color: "FFC000"})
	table.Row(4).Cell(3).AddParagraph("v1.3")
	table.Row(4).Cell(4).AddParagraph("Complex spanning")

	// 5. Advanced Paragraph Styling
	doc.AddHeading("2. Advanced Paragraph & Run Styling", 2)

	doc.AddParagraph("Standard left-aligned paragraph with some spacing before and after.",
		document.CellStyle{SpacingBefore: 6, SpacingAfter: 6})

	doc.AddParagraph("Centered paragraph with a different font size and color.",
		document.CellStyle{Horizontal: "center", Size: 24, Color: "C00000"})

	doc.AddParagraph("Right-aligned paragraph with indentation.",
		document.CellStyle{Horizontal: "right", Indent: 36})

	doc.AddParagraph("Paragraph with line spacing (double).",
		document.CellStyle{LineSpacing: 2.0})

	// Rich Text
	doc.AddRichParagraph([]document.TextSpan{
		{Text: "This is ", Style: document.CellStyle{}},
		{Text: "bold ", Style: document.CellStyle{Bold: true}},
		{Text: "and ", Style: document.CellStyle{}},
		{Text: "italic ", Style: document.CellStyle{Italic: true}},
		{Text: "and ", Style: document.CellStyle{}},
		{Text: "colored red ", Style: document.CellStyle{Color: "FF0000"}},
		{Text: "and ", Style: document.CellStyle{}},
		{Text: "larger", Style: document.CellStyle{Size: 32}},
		{Text: ".", Style: document.CellStyle{}},
	})

	// 6. Section Breaks and Different Page Orientations
	doc.AddHeading("3. Section Breaks & Layout", 2)
	doc.AddParagraph("The next page will be in landscape orientation.")

	// Add a new section with landscape orientation
	doc.AddSection(document.PageSettings{
		Orientation: "landscape",
		PaperType:   "A4",
	})

	doc.AddHeading("Landscape Section", 1)
	doc.AddParagraph("This content is on a landscape page. Ideal for wide tables or charts.")

	wideTable, _ := doc.AddTable(2, 6)
	wideTable.SetStyle("TableGrid").SetColumnWidths(1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
	for i := 0; i < 6; i++ {
		wideTable.Row(0).Cell(i).AddParagraph(fmt.Sprintf("Col %d", i+1), headerStyle)
		wideTable.Row(1).Cell(i).AddParagraph("Data")
	}

	// 7. Lists (Bulleted and Numbered)
	doc.AddHeading("4. Lists and Numbering", 2)
	doc.AddList([]string{"Requirement 1", "Requirement 2", "Requirement 3"}, true) // Numbered
	doc.AddList([]string{"Bullet A", "Bullet B", "Bullet C"}, false)               // Bulleted

	// Save the document
	f, err := os.Create("advanced_demo.docx")
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		return
	}
	defer f.Close()

	if err := doc.Save(ctx, f); err != nil {
		fmt.Printf("Error saving document: %v\n", err)
		return
	}

	fmt.Println("Advanced demo generated: advanced_demo.docx")
}
