package main

import (
	"context"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"time"

	"github.com/gsoultan/thoth/core"
	"github.com/gsoultan/thoth/document"
	"github.com/rs/zerolog"
)

func main() {
	// Ensure test image exists for the logo
	ensureTestImage()

	logger := zerolog.New(os.Stdout).With().Timestamp().Logger()
	thoth := core.New(logger)
	ctx := context.Background()

	logger.Info().Msg("--- PDF Quotation Example ---")

	pdf, err := thoth.PDF().New(ctx)
	if err != nil {
		logger.Error().Err(err).Msg("Failed to create PDF")
		return
	}
	defer pdf.Close()

	// Page Settings: A4 with standard margins
	_ = pdf.SetPageSettings(document.NewPageSettingsBuilder().
		WithPaperType(document.PaperA4).
		WithMargins(document.Margins{Top: 20, Bottom: 20, Left: 20, Right: 20}).
		Build())

	// Footer with page numbering
	footerStyle := document.NewCellStyleBuilder().Size(8).Color("808080").Align("center", "bottom").Build()
	_ = pdf.SetFooter("Page {n} of {nb} - Generated by Thoth PDF Engine", footerStyle)

	// 1. Header Section: Logo and "QUOTATION" Title
	if tbl, err := pdf.AddTable(1, 2); err == nil {
		_ = tbl.SetColumnWidths(350, 150)
		_ = tbl.Row(0).Cell(0).AddImage("test.png", 50, 50)
		_ = tbl.Row(0).Cell(1).AddParagraph("QUOTATION").
			Style(document.NewCellStyleBuilder().Bold().Size(24).Color("2E5481").Align("right", "center").Build())
	}

	_ = pdf.AddParagraph("\n", document.NewCellStyleBuilder().Size(10).Build())

	// 2. Company and Customer Info Section
	if tbl, err := pdf.AddTable(1, 2); err == nil {
		_ = tbl.SetColumnWidths(250, 250)

		// Left: From (Company Info)
		_ = tbl.Row(0).Cell(0).
			AddParagraph("FROM:").Style(document.NewCellStyleBuilder().Bold().Size(9).Color("808080").Build()).
			AddParagraph("Thoth Solutions Ltd.").Style(document.NewCellStyleBuilder().Bold().Size(12).Build()).
			AddParagraph("123 Document Street\nTech City, TC 12345\nUnited Kingdom\ncontact@thoth-solutions.com").
			Style(document.NewCellStyleBuilder().Size(10).Build())

		// Right: To (Customer Info)
		_ = tbl.Row(0).Cell(1).
			AddParagraph("BILL TO:").Style(document.NewCellStyleBuilder().Bold().Size(9).Color("808080").Align("right", "top").Build()).
			AddParagraph("Acme Global Industries").Style(document.NewCellStyleBuilder().Bold().Size(12).Align("right", "top").Build()).
			AddParagraph("456 Innovation Drive\nEnterprise Park, EP 67890\nAttn: Procurement Dept").
			Style(document.NewCellStyleBuilder().Size(10).Align("right", "top").Build())
	}

	_ = pdf.AddParagraph("\n", document.NewCellStyleBuilder().Size(10).Build())

	// 3. Quotation Meta Details (Date, Number, Expiry)
	if tbl, err := pdf.AddTable(1, 3); err == nil {
		_ = tbl.SetColumnWidths(166, 166, 166)

		boxStyle := document.NewCellStyleBuilder().Border().Padding(5).Align("center", "center").Build()
		labelStyle := document.NewCellStyleBuilder().Bold().Size(8).Color("808080").Build()

		_ = tbl.Row(0).Cell(0).
			AddParagraph("QUOTATION #").Style(labelStyle).
			AddParagraph("Q-2026-0042").Style(document.NewCellStyleBuilder().Bold().Build()).
			Style(boxStyle)

		_ = tbl.Row(0).Cell(1).
			AddParagraph("DATE").Style(labelStyle).
			AddParagraph(time.Now().Format("02 Jan 2006")).Style(document.NewCellStyleBuilder().Bold().Build()).
			Style(boxStyle)

		_ = tbl.Row(0).Cell(2).
			AddParagraph("EXPIRY DATE").Style(labelStyle).
			AddParagraph("27 Mar 2026").Style(document.NewCellStyleBuilder().Bold().Build()).
			Style(boxStyle)
	}

	_ = pdf.AddParagraph("\n", document.NewCellStyleBuilder().Size(15).Build())

	// 4. Line Items Table
	items := []struct {
		Desc  string
		Qty   int
		Price float64
	}{
		{"Thoth Enterprise PDF Engine - Site License", 1, 2499.00},
		{"Priority Support (12 Months)", 1, 499.00},
		{"Custom Word Template Integration", 3, 150.00},
		{"Excel Automation Module", 1, 750.00},
		{"Training Workshop (Remote)", 2, 200.00},
	}

	if tbl, err := pdf.AddTable(len(items)+1, 5); err == nil {
		_ = tbl.SetColumnWidths(40, 240, 60, 80, 80)

		headerStyle := document.NewCellStyleBuilder().
			Bold().
			Background("2E5481").
			Color("FFFFFF").
			Border().
			Align("center", "center").
			Padding(5).
			Build()

		_ = tbl.Row(0).Cell(0).AddParagraph("ITEM").Style(headerStyle)
		_ = tbl.Row(0).Cell(1).AddParagraph("DESCRIPTION").Style(headerStyle)
		_ = tbl.Row(0).Cell(2).AddParagraph("QTY").Style(headerStyle)
		_ = tbl.Row(0).Cell(3).AddParagraph("UNIT PRICE").Style(headerStyle)
		_ = tbl.Row(0).Cell(4).AddParagraph("TOTAL").Style(headerStyle)

		rowStyle := document.NewCellStyleBuilder().Border().Padding(5).Build()
		numStyle := document.NewCellStyleBuilder().Border().Align("right", "center").Padding(5).Build()

		subtotal := 0.0
		for i, item := range items {
			lineTotal := float64(item.Qty) * item.Price
			subtotal += lineTotal

			r := i + 1
			_ = tbl.Row(r).Cell(0).AddParagraph(fmt.Sprintf("%d", r)).Style(rowStyle)
			_ = tbl.Row(r).Cell(1).AddParagraph(item.Desc).Style(rowStyle)
			_ = tbl.Row(r).Cell(2).AddParagraph(fmt.Sprintf("%d", item.Qty)).Style(numStyle)
			_ = tbl.Row(r).Cell(3).AddParagraph(fmt.Sprintf("$%.2f", item.Price)).Style(numStyle)
			_ = tbl.Row(r).Cell(4).AddParagraph(fmt.Sprintf("$%.2f", lineTotal)).Style(numStyle)
		}

		// 5. Totals Section (another table for precise alignment)
		_ = pdf.AddParagraph("\n", document.NewCellStyleBuilder().Size(5).Build())

		if totalsTbl, err := pdf.AddTable(3, 2); err == nil {
			_ = totalsTbl.SetColumnWidths(420, 80)

			taxRate := 0.15
			taxAmount := subtotal * taxRate
			grandTotal := subtotal + taxAmount

			labelStyle := document.NewCellStyleBuilder().Align("right", "center").Padding(5).Build()
			valueStyle := document.NewCellStyleBuilder().Border().Align("right", "center").Padding(5).Build()

			_ = totalsTbl.Row(0).Cell(0).AddParagraph("Subtotal").Style(labelStyle)
			_ = totalsTbl.Row(0).Cell(1).AddParagraph(fmt.Sprintf("$%.2f", subtotal)).Style(valueStyle)

			_ = totalsTbl.Row(1).Cell(0).AddParagraph(fmt.Sprintf("Tax (%.0f%%)", taxRate*100)).Style(labelStyle)
			_ = totalsTbl.Row(1).Cell(1).AddParagraph(fmt.Sprintf("$%.2f", taxAmount)).Style(valueStyle)

			_ = totalsTbl.Row(2).Cell(0).AddParagraph("GRAND TOTAL").
				Style(document.NewCellStyleBuilder().Bold().Align("right", "center").Padding(5).Build())
			_ = totalsTbl.Row(2).Cell(1).AddParagraph(fmt.Sprintf("$%.2f", grandTotal)).
				Style(document.NewCellStyleBuilder().Bold().Background("F2F2F2").Border().Align("right", "center").Padding(5).Build())
		}
	}

	// 6. Terms and Conditions
	_ = pdf.AddParagraph("\n\nTERMS AND CONDITIONS", document.NewCellStyleBuilder().Bold().Size(12).Build())
	_ = pdf.AddParagraph("1. This quotation is valid for 30 days from the date of issue.\n"+
		"2. 50% upfront payment required to commence work.\n"+
		"3. Software licenses are subject to the standard Thoth EULA.\n"+
		"4. Delivery timeframe will be confirmed upon receipt of PO.",
		document.NewCellStyleBuilder().Size(9).Color("404040").LineSpacing(1.2).Build())

	_ = pdf.AddParagraph("\n\n", document.NewCellStyleBuilder().Size(20).Build())
	_ = pdf.AddParagraph("Thank you for your business!",
		document.NewCellStyleBuilder().Italic().Align("center", "center").Size(11).Color("2E5481").Build())

	if err := pdf.Export("quotation_output.pdf"); err != nil {
		logger.Error().Err(err).Msg("Failed to save PDF")
	} else {
		logger.Info().Msg("Successfully saved quotation_output.pdf")
	}
}

func ensureTestImage() {
	const path = "test.png"
	if _, err := os.Stat(path); err == nil {
		return
	}

	img := image.NewRGBA(image.Rect(0, 0, 100, 100))
	for y := 0; y < 100; y++ {
		for x := 0; x < 100; x++ {
			c := color.RGBA{46, 84, 129, 255} // Dark blue
			if x < 2 || x > 97 || y < 2 || y > 97 {
				c = color.RGBA{0, 0, 0, 255} // Black border
			}
			img.Set(x, y, c)
		}
	}

	f, err := os.Create(path)
	if err != nil {
		return
	}
	defer f.Close()
	_ = png.Encode(f, img)
}
