package main

import (
	"context"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"

	"github.com/gsoultan/thoth/core"
	"github.com/gsoultan/thoth/document"
	"github.com/rs/zerolog"
)

func main() {
	// 1. Generate transparent PNG for testing
	ensureTransparentImage()

	logger := zerolog.New(os.Stdout).With().Timestamp().Logger()
	thoth := core.New(logger)
	ctx := context.Background()

	logger.Info().Msg("--- Advanced Production PDF Example ---")

	pdf, err := thoth.PDF().New(ctx)
	if err != nil {
		logger.Error().Err(err).Msg("Failed to create PDF")
		return
	}
	defer pdf.Close()

	// 2. Metadata (Title, Author)
	_ = pdf.SetMetadata(document.Metadata{
		Title:       "Enterprise Sales Report 2026",
		Author:      "Thoth Report Engine",
		Subject:     "Production Grade PDF Generation",
		Keywords:    []string{"enterprise", "production", "robust", "layout"},
		Description: "A comprehensive demonstration of Thoth PDF capabilities.",
	})

	// 3. Global Header/Footer
	headerStyle := document.NewCellStyleBuilder().Bold().Size(14).Color("4F81BD").Align("center", "center").Build()
	_ = pdf.SetHeader("CONFIDENTIAL ENTERPRISE REPORT", headerStyle)

	footerStyle := document.NewCellStyleBuilder().Size(8).Color("808080").Align("right", "center").Build()
	_ = pdf.SetFooter("Generated by Thoth | Page {n} of {nb}", footerStyle)

	// 4. Page 1: Portrait A4 with TOC
	_ = pdf.SetPageSettings(document.NewPageSettingsBuilder().WithPaperType(document.PaperA4).Build())

	_ = pdf.AddTableOfContents()

	_ = pdf.AddPageBreak()

	// 5. Section 1: Portrait with transparent image
	_ = pdf.AddHeading("Transparent Image Test", 1)
	_ = pdf.AddBookmark("Section-1") // Target for TOC

	_ = pdf.AddParagraph("The logo below is a transparent PNG. In professional production PDFs, alpha channel must be preserved using SMasks.", document.NewCellStyleBuilder().Size(11).SpacingAfter(20).Build())

	// Drawing a colored box behind to prove transparency
	_ = pdf.DrawRect(100, 500, 100, 100, document.NewCellStyleBuilder().Background("FFFF00").Build())
	_ = pdf.InsertImage("transparent.png", 60, 60, document.NewCellStyleBuilder().Align("center", "center").Build())

	_ = pdf.AddPageBreak()

	// 6. Section 2: Landscape with repeating table headers
	logger.Info().Msg("Adding Landscape Section...")
	landscape := document.NewPageSettingsBuilder().
		WithPaperType(document.PaperA4).
		WithOrientation(document.OrientationLandscape).
		Build()
	_ = pdf.AddSection(landscape) // This should switch page dimensions

	_ = pdf.AddHeading("Large Data (Landscape)", 1, document.NewCellStyleBuilder().Name("Heading1").Build())
	_ = pdf.AddBookmark("Section-2")

	_ = pdf.AddParagraph("This table spans multiple pages in landscape mode to test header repetition and per-page dimensions.", document.NewCellStyleBuilder().Size(10).Build())

	if tbl, err := pdf.AddTable(50, 4); err == nil {
		hStyle := document.NewCellStyleBuilder().Bold().Background("4F81BD").Color("FFFFFF").Border().Align("center", "center").Build()
		_ = tbl.Row(0).Cell(0).AddParagraph("ID").Style(hStyle)
		_ = tbl.Row(0).Cell(1).AddParagraph("Department").Style(hStyle)
		_ = tbl.Row(0).Cell(2).AddParagraph("Utilization (%)").Style(hStyle)
		_ = tbl.Row(0).Cell(3).AddParagraph("Performance").Style(hStyle)

		dStyle := document.NewCellStyleBuilder().Border().Build()
		for i := 1; i < 50; i++ {
			_ = tbl.Row(i).Cell(0).AddParagraph(fmt.Sprintf("%04d", i)).Style(dStyle)
			_ = tbl.Row(i).Cell(1).AddParagraph("Engineering").Style(dStyle)
			_ = tbl.Row(i).Cell(2).AddParagraph("85%").Style(dStyle)
			_ = tbl.Row(i).Cell(3).AddParagraph("High").Style(dStyle)
		}
	}

	_ = pdf.AddPageBreak()

	// 7. Section 3: Interactive Forms
	_ = pdf.SetPageSettings(document.NewPageSettingsBuilder().WithPaperType(document.PaperA4).WithOrientation(document.OrientationPortrait).Build())
	_ = pdf.AddHeading("Interactive Forms", 1, document.NewCellStyleBuilder().Name("Heading1").Build())
	_ = pdf.AddBookmark("Section-3")

	_ = pdf.AddParagraph("Feedback Form:", document.NewCellStyleBuilder().Bold().Size(12).SpacingAfter(10).Build())

	_ = pdf.AddParagraph("Your Name:", document.NewCellStyleBuilder().Size(10).Build())
	_ = pdf.AddTextField("user_name", 120, 0, 200, 15) // Absolute positioning in PDF

	_ = pdf.AddParagraph("\nSubscribe to updates:", document.NewCellStyleBuilder().Size(10).Build())
	_ = pdf.AddCheckbox("subscribe", 150, 0)

	// 8. Save
	if err := pdf.Export("production_output.pdf"); err != nil {
		logger.Error().Err(err).Msg("Failed to save PDF")
	} else {
		logger.Info().Msg("Successfully saved production_output.pdf")
	}
}

func ensureTransparentImage() {
	const path = "transparent.png"
	// Create an image with a transparent background and a blue circle
	img := image.NewRGBA(image.Rect(0, 0, 100, 100))

	// Draw a blue circle
	for y := 0; y < 100; y++ {
		for x := 0; x < 100; x++ {
			dx := float64(x - 50)
			dy := float64(y - 50)
			if dx*dx+dy*dy < 40*40 {
				img.Set(x, y, color.RGBA{0, 122, 255, 255}) // Opaque Blue
			} else if dx*dx+dy*dy < 45*45 {
				img.Set(x, y, color.RGBA{0, 0, 0, 128}) // Translucent black border
			}
		}
	}

	f, _ := os.Create(path)
	defer f.Close()
	_ = png.Encode(f, img)
}
