package main

import (
	"context"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"time"

	"github.com/gsoultan/thoth/core"
	"github.com/gsoultan/thoth/document"
	"github.com/rs/zerolog"
)

func main() {
	// Ensure test image exists for the logo
	ensureTestImage()

	logger := zerolog.New(os.Stdout).With().Timestamp().Logger()
	thoth := core.New(logger)
	ctx := context.Background()

	logger.Info().Msg("--- Word Quotation Example ---")

	word, err := thoth.Word().New(ctx)
	if err != nil {
		logger.Error().Err(err).Msg("Failed to create Word document")
		return
	}
	defer word.Close()

	// Page Settings: A4 with standard margins
	_ = word.SetPageSettings(document.NewPageSettingsBuilder().
		WithPaperType(document.PaperA4).
		WithMargins(document.Margins{Top: 20, Bottom: 20, Left: 20, Right: 20}).
		Build())

	// Footer with page numbering
	footerStyle := document.NewCellStyleBuilder().Size(8).Color("808080").Align("center", "bottom").Build()
	_ = word.SetFooter("Page {n} of {nb} - Generated by Thoth Word Engine", footerStyle)

	// 1. Header Section: Logo and "QUOTATION" Title
	if tbl, err := word.AddTable(1, 2); err == nil {
		_ = tbl.SetColumnWidths(350, 150)
		_ = tbl.Row(0).Cell(0).AddImage("logo.png", 50, 50)
		_ = tbl.Row(0).Cell(1).AddParagraph("QUOTATION").
			Style(document.NewCellStyleBuilder().Bold().Size(24).Color("2E5481").Align("right", "center").Build())
	}

	_ = word.AddParagraph("", document.NewCellStyleBuilder().Size(10).Build())

	// 2. Company and Customer Info Section
	if tbl, err := word.AddTable(1, 2); err == nil {
		_ = tbl.SetColumnWidths(250, 250)

		// Left: From (Company Info)
		fromCell := tbl.Row(0).Cell(0)
		_ = fromCell.AddParagraph("FROM:").Style(document.NewCellStyleBuilder().Bold().Size(9).Color("808080").Build())
		_ = fromCell.AddParagraph("Thoth Solutions Ltd.").Style(document.NewCellStyleBuilder().Bold().Size(12).Build())
		_ = fromCell.AddParagraph("123 Document Street").Style(document.NewCellStyleBuilder().Size(10).Build())
		_ = fromCell.AddParagraph("Tech City, TC 12345").Style(document.NewCellStyleBuilder().Size(10).Build())
		_ = fromCell.AddParagraph("United Kingdom").Style(document.NewCellStyleBuilder().Size(10).Build())
		_ = fromCell.AddParagraph("contact@thoth-solutions.com").Style(document.NewCellStyleBuilder().Size(10).Build())

		// Right: To (Customer Info)
		toCell := tbl.Row(0).Cell(1)
		alignRight := document.NewCellStyleBuilder().Align("right", "top")
		_ = toCell.AddParagraph("BILL TO:").Style(alignRight.Bold().Size(9).Color("808080").Build())
		_ = toCell.AddParagraph("Acme Global Industries").Style(alignRight.Bold().Size(12).Build())
		_ = toCell.AddParagraph("456 Innovation Drive").Style(alignRight.Size(10).Build())
		_ = toCell.AddParagraph("Enterprise Park, EP 67890").Style(alignRight.Size(10).Build())
		_ = toCell.AddParagraph("Attn: Procurement Dept").Style(alignRight.Size(10).Build())
	}

	_ = word.AddParagraph("", document.NewCellStyleBuilder().Size(10).Build())

	// 3. Quotation Meta Details (Date, Number, Expiry)
	if tbl, err := word.AddTable(1, 3); err == nil {
		_ = tbl.SetColumnWidths(166, 166, 166)

		boxStyle := document.NewCellStyleBuilder().Border().Padding(5).Align("center", "center").Build()
		labelStyle := document.NewCellStyleBuilder().Bold().Size(8).Color("808080").Build()

		_ = tbl.Row(0).Cell(0).
			AddParagraph("QUOTATION #").Style(labelStyle).
			AddParagraph("Q-2026-0042").Style(document.NewCellStyleBuilder().Bold().Build()).
			Style(boxStyle)

		_ = tbl.Row(0).Cell(1).
			AddParagraph("DATE").Style(labelStyle).
			AddParagraph(time.Now().Format("02 Jan 2006")).Style(document.NewCellStyleBuilder().Bold().Build()).
			Style(boxStyle)

		_ = tbl.Row(0).Cell(2).
			AddParagraph("EXPIRY DATE").Style(labelStyle).
			AddParagraph("27 Mar 2026").Style(document.NewCellStyleBuilder().Bold().Build()).
			Style(boxStyle)
	}

	_ = word.AddParagraph("", document.NewCellStyleBuilder().Size(15).Build())

	// 4. Line Items Table
	items := []struct {
		Desc  string
		Qty   int
		Price float64
	}{
		{"Thoth Enterprise Word Engine - Site License", 1, 2499.00},
		{"Priority Support (12 Months)", 1, 499.00},
		{"Custom Word Template Integration", 3, 150.00},
		{"Excel Automation Module", 1, 750.00},
		{"Training Workshop (Remote)", 2, 200.00},
	}

	if tbl, err := word.AddTable(len(items)+1, 5); err == nil {
		_ = tbl.SetColumnWidths(40, 240, 60, 80, 80)

		headerStyle := document.NewCellStyleBuilder().
			Bold().
			Background("2E5481").
			Color("FFFFFF").
			Border().
			Align("center", "center").
			Padding(5).
			Build()

		_ = tbl.Row(0).Cell(0).AddParagraph("ITEM").Style(headerStyle)
		_ = tbl.Row(0).Cell(1).AddParagraph("DESCRIPTION").Style(headerStyle)
		_ = tbl.Row(0).Cell(2).AddParagraph("QTY").Style(headerStyle)
		_ = tbl.Row(0).Cell(3).AddParagraph("UNIT PRICE").Style(headerStyle)
		_ = tbl.Row(0).Cell(4).AddParagraph("TOTAL").Style(headerStyle)

		rowStyle := document.NewCellStyleBuilder().Border().Padding(5).Build()
		numStyle := document.NewCellStyleBuilder().Border().Align("right", "center").Padding(5).Build()

		subtotal := 0.0
		for i, item := range items {
			lineTotal := float64(item.Qty) * item.Price
			subtotal += lineTotal

			r := i + 1
			_ = tbl.Row(r).Cell(0).AddParagraph(fmt.Sprintf("%d", r)).Style(rowStyle)
			_ = tbl.Row(r).Cell(1).AddParagraph(item.Desc).Style(rowStyle)
			_ = tbl.Row(r).Cell(2).AddParagraph(fmt.Sprintf("%d", item.Qty)).Style(numStyle)
			_ = tbl.Row(r).Cell(3).AddParagraph(fmt.Sprintf("%.2f", item.Price)).Style(numStyle)
			_ = tbl.Row(r).Cell(4).AddParagraph(fmt.Sprintf("%.2f", lineTotal)).Style(numStyle)
		}

		// 5. Totals Section
		tax := subtotal * 0.20
		total := subtotal + tax

		_ = word.AddParagraph("", document.NewCellStyleBuilder().Size(10).Build())

		if summaryTbl, err := word.AddTable(3, 2); err == nil {
			_ = summaryTbl.SetColumnWidths(400, 100)

			labelStyle := document.NewCellStyleBuilder().Bold().Align("right", "center").Padding(5).Build()
			valStyle := document.NewCellStyleBuilder().Align("right", "center").Padding(5).Border().Build()
			totalValStyle := document.NewCellStyleBuilder().Bold().Align("right", "center").Padding(5).Background("F0F0F0").Border().Build()

			_ = summaryTbl.Row(0).Cell(0).AddParagraph("SUBTOTAL").Style(labelStyle)
			_ = summaryTbl.Row(0).Cell(1).AddParagraph(fmt.Sprintf("%.2f", subtotal)).Style(valStyle)

			_ = summaryTbl.Row(1).Cell(0).AddParagraph("TAX (20%)").Style(labelStyle)
			_ = summaryTbl.Row(1).Cell(1).AddParagraph(fmt.Sprintf("%.2f", tax)).Style(valStyle)

			_ = summaryTbl.Row(2).Cell(0).AddParagraph("TOTAL").Style(labelStyle)
			_ = summaryTbl.Row(2).Cell(1).AddParagraph(fmt.Sprintf("%.2f", total)).Style(totalValStyle)
		}
	}

	_ = word.AddParagraph("", document.NewCellStyleBuilder().Size(10).Build())
	_ = word.AddParagraph("", document.NewCellStyleBuilder().Size(10).Build())

	// 6. Terms & Conditions
	_ = word.AddParagraph("TERMS & CONDITIONS", document.NewCellStyleBuilder().Bold().Size(12).Build())
	tcStyle := document.NewCellStyleBuilder().Size(9).Color("444444").Build()
	_ = word.AddParagraph("1. Please include the quotation number on your purchase order.", tcStyle)
	_ = word.AddParagraph("2. This quotation is valid for 30 days from the date of issue.", tcStyle)
	_ = word.AddParagraph("3. Payment terms: Net 30 days from date of invoice.", tcStyle)
	_ = word.AddParagraph("4. Support services are subject to the Thoth SLA agreement.", tcStyle)

	// Export the final document
	outputPath := "quotation_output.docx"
	if err := word.Export(outputPath); err != nil {
		logger.Error().Err(err).Msg("Failed to export Word document")
		return
	}

	logger.Info().Str("path", outputPath).Msg("Word quotation generated successfully")
}

func ensureTestImage() {
	if _, err := os.Stat("logo.png"); err == nil {
		return
	}
	img := image.NewRGBA(image.Rect(0, 0, 100, 100))
	for y := 0; y < 100; y++ {
		for x := 0; x < 100; x++ {
			img.Set(x, y, color.RGBA{46, 84, 129, 255}) // Theme blue
		}
	}
	f, _ := os.Create("logo.png")
	defer f.Close()
	_ = png.Encode(f, img)
}
