package main

import (
	"context"
	"fmt"
	"os"

	"github.com/gsoultan/thoth/document"
	"github.com/gsoultan/thoth/word"
)

func main() {
	ctx := context.Background()

	// Create a new Word document directly
	doc := word.NewDocument().(document.WordProcessor)
	defer doc.Close()

	// 1. Metadata
	doc.SetMetadata(document.Metadata{
		Title:  "Enterprise Report",
		Author: "Junie AI",
	})

	// 2. Header and Footer
	doc.SetHeader("CONFIDENTIAL - Enterprise Grade Document", document.CellStyle{Horizontal: "center", Italic: true})
	doc.SetFooter("Page 1 of 1", document.CellStyle{Horizontal: "right"})

	// 3. Watermark
	doc.SetWatermark("DRAFT", document.CellStyle{Color: "FF0000"})

	// 4. Content - Heading
	doc.AddHeading("Executive Summary", 1, document.CellStyle{Bold: true, Color: "2F5496"})

	// 5. Content - Paragraph with Hyperlink
	doc.AddParagraph("This is an automated report generated by the Thoth library. For more information, visit our website.")
	doc.AddHyperlink("Thoth Repository", "https://github.com/gsoultan/thoth", document.CellStyle{Color: "0000FF"})

	// 6. Lists - Real OOXML Numbering
	doc.AddHeading("Key Features", 2)
	doc.AddList([]string{
		"High-performance document generation",
		"Enterprise-grade OOXML support",
		"Extensible modular architecture",
	}, false) // Bulleted list

	doc.AddHeading("Next Steps", 2)
	doc.AddList([]string{
		"Initialize the environment",
		"Run the integration tests",
		"Deploy to production",
	}, true) // Numbered list

	// 7. Table with Column Widths and Styles
	doc.AddHeading("Financial Overview", 2)
	table, err := doc.AddTable(3, 3)
	if err != nil {
		fmt.Printf("Error adding table: %v\n", err)
		return
	}

	table.SetColumnWidths(1.5, 2.0, 1.5).SetStyle("TableGrid")

	// Table Header
	headerStyle := document.CellStyle{Bold: true, Background: "D9D9D9", Horizontal: "center"}
	table.Row(0).Cell(0).AddParagraph("Category", headerStyle)
	table.Row(0).Cell(1).AddParagraph("Description", headerStyle)
	table.Row(0).Cell(2).AddParagraph("Amount", headerStyle)

	// Table Body
	table.Row(1).Cell(0).AddParagraph("Revenue")
	table.Row(1).Cell(1).AddParagraph("Q1 Sales Revenue")
	table.Row(1).Cell(2).AddParagraph("$1,250,000")

	table.Row(2).Cell(0).AddParagraph("Expenses")
	table.Row(2).Cell(1).AddParagraph("Operating Costs")
	table.Row(2).Cell(2).AddParagraph("$850,000")

	// 8. Footnotes
	doc.AddParagraph("The financial data is based on the latest audit report.")
	doc.AddFootnote("Audit conducted by External Firm on Feb 2026.")

	// 9. Bookmarks
	doc.AddBookmark("EndReport")

	// 10. Form Fields (Advanced)
	doc.AddHeading("Feedback Form", 2)
	doc.AddParagraph("Please enter your name:")
	doc.AddTextField("UserName", 0, 0, 0, 0)
	doc.AddParagraph("Subscribe to newsletter:")
	doc.AddCheckbox("Subscribe", 0, 0)

	// Save the document
	f, err := os.Create("enterprise_report.docx")
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		return
	}
	defer f.Close()

	if err := doc.Save(ctx, f); err != nil {
		fmt.Printf("Error saving document: %v\n", err)
		return
	}

	fmt.Println("Enterprise report generated: enterprise_report.docx")
}
